In [43]:
import pandas as pd
import numpy as np

In [46]:
# 1. Load dataset
df_raw = pd.read_csv('../data/raw/crop_data.csv')

In [ ]:
# 2. Standardize Column Names
df_raw.columns = (
    df_raw.columns
    .str.strip()
    .str.replace(" ", "_", regex=False)
    .str.replace("-", "_", regex=False)
)

In [ ]:

# 3. Clean Text Columns
text_cols = ["State", "District", "Crop", "Season"]

for col in text_cols:
    if col in df_raw.columns:
        df_raw[col] = df_raw[col].astype(str).str.strip()

Reshaping the Data

In [28]:
# 2. Reshape (Melt) the 'Area' columns
df_area = df_raw.melt(id_vars=['State', 'District', 'Crop', 'Season'], 
                  value_vars=['Area-2022-23', 'Area-2023-24', 'Area-2024-25'],
                  var_name='Year_Type', value_name='Area')
df_area['Crop_Year'] = df_area['Year_Type'].str.replace('Area-', '')

# 3. Reshape (Melt) the 'Production' columns
df_prod = df_raw.melt(id_vars=['State', 'District', 'Crop', 'Season'], 
                  value_vars=['Production-2022-23', 'Production-2023-24', 'Production-2024-25'],
                  var_name='Year_Type', value_name='Production')

# 4. Reshape (Melt) the 'Yield' columns
df_yield = df_raw.melt(id_vars=['State', 'District', 'Crop', 'Season'], 
                   value_vars=['Yield-2022-23', 'Yield-2023-24', 'Yield-2024-25'],
                   var_name='Year_Type', value_name='Yield')

In [31]:
# 5. Combine them back together into the standard Long Format
df_long = df_area[['State', 'District', 'Crop', 'Season', 'Crop_Year', 'Area']].copy()
df_long['Production'] = df_prod['Production']
df_long['Yield'] = df_yield['Yield']

print("After Melting:", df_long.shape)
df_long.tail()

After Melting: (84807, 8)

,State,District,Crop,Season,Crop_Year,Area,Production,Yield
84802,West Bengal,Purulia,Total Pulses,Total,2024-25,NaN,NaN,NaN
84803,West Bengal,Purulia,Total Food Grains,Kharif,2024-25,NaN,NaN,NaN
84804,West Bengal,Purulia,Total Food Grains,Rabi,2024-25,NaN,NaN,NaN
84805,West Bengal,Purulia,Total Food Grains,Summer,2024-25,NaN,NaN,NaN
84806,West Bengal,Purulia,Total Food Grains,Total,2024-25,NaN,NaN,NaN

Cleaning the missing values

In [33]:
# Remove "Total" season rows
df_clean = df_long[df_long["Season"] != "Total"]

# Drop missing values
df_clean = df_clean.dropna(subset=["Area", "Production", "Yield"])

# Remove invalid Area
df_clean = df_clean[df_clean["Area"] > 0]

# Remove Production = 0 (important fix)
df_clean = df_clean[df_clean["Production"] > 0]

# Reset index
df_clean = df_clean.reset_index(drop=True)

print("After Cleaning:", df_clean.shape)
df_clean.head()

After Cleaning: (23755, 8)

,State,District,Crop,Season,Crop_Year,Area,Production,Yield
0,Andaman And Nicobar Islands,North And Middle Andaman,Rice,Kharif,2022-23,0.05,0.10,2110.0
1,Andaman And Nicobar Islands,North And Middle Andaman,Cereals,Kharif,2022-23,0.05,0.10,2110.0
2,Andaman And Nicobar Islands,North And Middle Andaman,Total Food Grains,Kharif,2022-23,0.05,0.10,2110.0
3,Andhra Pradesh,Alluri Sitharama Raju,Rice,Kharif,2022-23,0.57,1.69,2987.0
4,Andhra Pradesh,Alluri Sitharama Raju,Rice,Rabi,2022-23,0.02,0.06,2999.0

In [38]:
print(f"Rows before final filter: {len(df_clean)}")
print(df_clean.columns)
for col in df_clean.columns:
    print(f"\n{col}:")
    print(df_clean[col].unique())

Rows before final filter: 23755
Index(['State', 'District', 'Crop', 'Season', 'Crop_Year', 'Area',
       'Production', 'Yield'],
      dtype='str')

State:
<StringArray>
[                 'Andaman And Nicobar Islands',
                               'Andhra Pradesh',
                            'Arunachal Pradesh',
                                        'Assam',
                                        'Bihar',
                                   'Chandigarh',
                                 'Chhattisgarh',
                                          'Goa',
                                      'Gujarat',
                                      'Haryana',
                             'Himachal Pradesh',
                            'Jammu And Kashmir',
                                    'Jharkhand',
                                    'Karnataka',
                                       'Kerala',
                                       'Ladakh',
                               'Madhya Pradesh',
                                  'Maharashtra',
                                      'Manipur',
                                    'Meghalaya',
                                      'Mizoram',
                                     'Nagaland',
                                       'Odisha',
                                   'Puducherry',
                                       'Punjab',
                                    'Rajasthan',
                                       'Sikkim',
                                   'Tamil Nadu',
                                    'Telangana',
 'The Dadra And Nagar Haveli And Daman And Diu',
                                      'Tripura',
                                'Uttar Pradesh',
                                  'Uttarakhand',
                                  'West Bengal']
Length: 34, dtype: str

District:
<StringArray>
[   'North And Middle Andaman',       'Alluri Sitharama Raju',
                  'Anakapalli',                   'Anantapur',
                   'Annamayya',                     'Bapatla',
                    'Chittoor', 'Dr. B.R. Ambedkar Konaseema',
               'East Godavari',                       'Eluru',
 ...
                     'Mauganj',                   'Pandhurna',
                     'Balotra',                      'Beawar',
                        'Deeg',            'Didwana Kuchaman',
            'Khairthal-Tijara',             'Kotputli-Behror',
                     'Phalodi',                    'Salumbar']
Length: 738, dtype: str

Crop:
<StringArray>
[                     'Rice',                   'Cereals',
         'Total Food Grains',                     'Maize',
                      'Ragi',             'Small Millets',
 'Shree Anna /Nutri Cereals',      'Nutri/Coarse Cereals',
                      'Urad',                     'Bajra',
                     'Moong',                     'Jowar',
                       'Tur',                      'Gram',
              'Other Pulses',                     'Wheat',
                    'Lentil',                    'Barley']
Length: 18, dtype: str

Season:
<StringArray>
['Kharif', 'Rabi', 'Summer']
Length: 3, dtype: str

Crop_Year:
<StringArray>
['2022-23', '2023-24', '2024-25']
Length: 3, dtype: str

Area:
[5.000e-02 5.700e-01 2.000e-02 4.000e-02 1.000e-02 1.500e-01 1.700e-01
 2.200e-01 7.800e-01 8.000e-01 6.000e-02 5.800e-01 5.900e-01 9.000e-02
 3.000e-02 6.000e-01 1.300e-01 2.100e-01 1.200e-01 4.300e-01 6.100e-01
 1.020e+00 8.400e-01 1.100e-01 1.400e-01 8.000e-02 9.900e-01 1.600e-01
 4.000e-01 4.800e-01 1.010e+00 6.400e-01 2.600e-01 1.040e+00 1.230e+00
 2.300e-01 5.600e-01 7.100e-01 7.200e-01 7.300e-01 7.600e-01 1.000e-01
 6.500e-01 7.900e-01 6.700e-01 8.900e-01 3.200e-01 2.900e-01 9.000e-01
 9.200e-01 7.700e-01 6.200e-01 3.800e-01 7.000e-02 6.600e-01 9.100e-01
 7.500e-01 1.630e+00 1.310e+00 1.640e+00 1.490e+00 1.800e-01 2.000e-01
 4.900e-01 3.400e-01 2.500e-01 5.500e-01 4.700e-01 1.190e+00 8.100e-01
 5.200e-01 1.590e+00 1.610e+00 4.600e-01 2.800e-01 5.400e-01 3.900e-01
 1.900e-01 2.400e-01 8.500e-01 1.260e+00 2.700e-01 1.270e+00 1.460e+00
 7.400e-01 1.510e+00 1.620e+00 9.400e-01 1.060e+00 3.000e-01 7.000e-01
 1.080e+00 5.300e-01 4.100e-01 4.200e-01 3.500e-01 3.600e-01 4.500e-01
 3.300e-01 1.180e+00 1.210e+00 6.900e-01 8.300e-01 8.800e-01 9.700e-01
 6.800e-01 8.700e-01 3.700e-01 5.000e-01 5.100e-01 1.000e+00 1.470e+00
 1.380e+00 2.420e+00 2.820e+00 8.600e-01 1.100e+00 1.150e+00 1.170e+00
 1.140e+00 2.170e+00 2.260e+00 1.690e+00 1.740e+00 4.400e-01 1.110e+00
 1.130e+00 1.350e+00 2.460e+00 2.500e+00 1.070e+00 1.030e+00 3.100e-01
 6.300e-01 1.160e+00 2.190e+00 2.280e+00 2.300e+00 1.930e+00 2.120e+00
 1.240e+00 1.820e+00 9.600e-01 1.370e+00 2.240e+00 2.000e+00 1.980e+00
 3.980e+00 4.020e+00 1.120e+00 1.730e+00 8.200e-01 9.300e-01 1.830e+00
 1.860e+00 1.520e+00 1.940e+00 1.950e+00 2.030e+00 2.040e+00 1.300e+00
 1.280e+00 1.570e+00 2.150e+00 2.220e+00 1.400e+00 1.840e+00 1.850e+00
 1.390e+00 1.420e+00 1.440e+00 1.500e+00 1.550e+00 1.560e+00 1.710e+00
 1.330e+00 1.870e+00 1.970e+00 1.200e+00 2.940e+00 3.020e+00 1.320e+00
 1.660e+00 1.760e+00 1.250e+00 1.290e+00 1.530e+00 2.070e+00 1.220e+00
 1.720e+00 1.700e+00 1.790e+00 1.650e+00 1.050e+00 1.430e+00 9.800e-01
 2.080e+00 2.110e+00 2.200e+00 9.500e-01 2.020e+00 1.810e+00 1.800e+00
 2.700e+00 2.720e+00 2.740e+00 1.480e+00 1.600e+00 1.750e+00 1.680e+00
 1.540e+00 1.880e+00 1.340e+00 2.140e+00 2.440e+00 3.240e+00 2.060e+00
 2.380e+00 2.600e+00 2.360e+00 2.400e+00 2.680e+00 2.690e+00 4.770e+00
 5.580e+00 1.900e+00 2.010e+00 3.070e+00 2.230e+00 2.370e+00 2.430e+00
 3.680e+00 4.740e+00 1.360e+00 3.060e+00 3.140e+00 2.090e+00 3.460e+00
 3.150e+00 3.250e+00 1.990e+00 4.570e+00 3.080e+00 3.610e+00 3.750e+00
 4.110e+00 4.300e+00 3.700e+00 2.880e+00 3.280e+00 3.050e+00 3.780e+00
 4.390e+00 2.480e+00 1.890e+00 2.330e+00 1.580e+00 2.660e+00 3.030e+00
 3.350e+00 2.100e+00 2.250e+00 1.960e+00 2.320e+00 3.130e+00 2.410e+00
 2.050e+00 2.470e+00 2.670e+00 2.850e+00 2.890e+00 2.900e+00 3.190e+00
 4.340e+00 4.590e+00 2.960e+00 2.800e+00 3.470e+00 4.120e+00 3.540e+00
 5.460e+00 2.650e+00 3.260e+00 3.120e+00 3.760e+00 3.430e+00 4.010e+00
 4.070e+00 1.910e+00 2.830e+00 2.520e+00 3.180e+00 4.530e+00 3.270e+00
 5.020e+00 3.880e+00 3.810e+00 1.770e+00 1.450e+00 2.310e+00 2.290e+00
 2.760e+00 4.050e+00 4.260e+00 2.570e+00 2.930e+00 1.090e+00 1.780e+00
 2.510e+00 3.160e+00 4.950e+00 1.410e+00 3.660e+00 3.000e+00 2.540e+00
 2.550e+00 2.590e+00 2.450e+00 2.340e+00 2.390e+00 3.920e+00 3.440e+00
 9.970e+00 1.001e+01 1.225e+01 2.730e+00 3.390e+00 3.600e+00 4.800e+00
 2.620e+00 3.330e+00 5.950e+00 7.930e+00 2.950e+00 2.180e+00 3.550e+00
 4.690e+00 3.670e+00 4.660e+00 4.580e+00 5.010e+00 8.150e+00 6.560e+00
 1.000e+01 3.710e+00 3.310e+00 2.780e+00 1.670e+00 2.130e+00 1.920e+00
 2.210e+00 2.490e+00 2.640e+00 3.410e+00 2.160e+00 2.630e+00 3.210e+00
 3.820e+00 2.910e+00 2.870e+00 2.610e+00 2.770e+00 3.770e+00 3.690e+00
 2.580e+00 5.660e+00 6.330e+00 2.350e+00 2.860e+00 3.400e+00 2.530e+00
 2.710e+00 3.890e+00 4.960e+00 3.530e+00 3.640e+00 4.100e+00 3.200e+00
 3.560e+00 2.270e+00 3.630e+00 2.920e+00 4.470e+00 3.570e+00 4.240e+00
 3.490e+00 4.510e+00 4.180e+00 3.370e+00 4.310e+00 3.110e+00 3.500e+00
 2.970e+00 2.980e+00 3.220e+00 3.230e+00 9.780e+00 9.790e+00 1.248e+01
 3.790e+00 5.280e+00 7.800e+00 4.200e+00 3.040e+00 4.210e+00 2.560e+00
 4.440e+00 4.760e+00 8.270e+00 2.810e+00 6.460e+00 9.800e+00 3.450e+00
 4.360e+00 3.720e+00 3.740e+00 3.590e+00 3.300e+00 2.790e+00 6.170e+00
 6.990e+00 2.750e+00 5.210e+00 6.240e+00 3.010e+00 3.510e+00 4.520e+00
 4.150e+00 4.170e+00 3.420e+00 4.320e+00 4.280e+00 4.370e+00 3.580e+00
 3.090e+00 3.650e+00 4.920e+00 4.090e+00 4.560e+00 6.910e+00 8.010e+00
 5.520e+00 7.320e+00 3.870e+00 3.320e+00 5.570e+00]

Production:
[0.1  1.69 0.06 ... 8.44 7.85 5.96]

Yield:
[2110. 2987. 2999. ... 2637. 4307. 4281.]

In [41]:
df_clean = df_clean[df_clean['Season'].str.strip() != 'Total']
target_crops = [
    'Rice', 'Maize', 'Wheat', 'Ragi', 'Bajra', 'Jowar', 'Barley', 
    'Tur', 'Urad', 'Moong', 'Gram', 'Lentil'
]

df_focused = df_clean[df_clean['Crop'].str.strip().isin(target_crops)]

In [42]:
print("\nMissing Values:")
print(df_clean.isnull().sum())

print("\nZero Values in Numeric Columns:")
print(df_clean.select_dtypes(include="number").eq(0).sum())

print("\nBasic Statistics:")
df_clean.describe()

Missing Values:
State         0
District      0
Crop          0
Season        0
Crop_Year     0
Area          0
Production    0
Yield         0
dtype: int64

Zero Values in Numeric Columns:
Area          0
Production    0
Yield         0
dtype: int64

Basic Statistics:

               Area    Production         Yield
count  23755.000000  23755.000000  23755.000000
mean       0.454016      1.196613   2341.595369
std        0.742368      2.077742   1585.227066
min        0.010000      0.010000     15.000000
25%        0.030000      0.040000   1211.000000
50%        0.120000      0.230000   2078.000000
75%        0.600000      1.430000   3164.000000
max       12.480000     18.660000  44815.000000

In [13]:
print(f"Final model-ready rows: {len(df_focused)}")
print("\n--- Final Unique Crops in Dataset ---")
print(df_focused['Crop'].unique())
print("\n--- Final Unique Seasons in Dataset ---")
print(df_focused['Season'].unique())
print("\n--- Final Unique Crop Years in Dataset ---")
print(df_focused['Crop_Year'].unique())

Final model-ready rows: 11057

--- Final Unique Crops in Dataset ---
<StringArray>
[  'Rice',  'Maize',   'Ragi',    'Tur',   'Urad',  'Moong',  'Bajra',
  'Jowar',   'Gram',  'Wheat', 'Lentil', 'Barley']
Length: 12, dtype: str

--- Final Unique Seasons in Dataset ---
<StringArray>
['Kharif', 'Rabi', 'Summer']
Length: 3, dtype: str

--- Final Unique Crop Years in Dataset ---
<StringArray>
['2022-23', '2023-24', '2024-25']
Length: 3, dtype: str

In [37]:
df_clean[df_clean['Production'] == 0][['Area', 'Production', 'Yield']].head()

Empty DataFrame
Columns: [Area, Production, Yield]
Index: []